version: '3'

services:
    db:
        image: mongo:5
        restart: always
        ports:
            - 27017:27017 #port del equipo : port del contenedor
        environment:
            MONGODB_DATABASE: nest-pokemon
        volumes:
            - ./mongo:/data/db #carpeta en proyecto: carpeta en contenedor
